{% set scip_version = "7.0.2" %}
{% set soplex_version = "5.0.2" %}
{% set gcg_version = "3.0.4" %}
{% set zimpl_version = "3.4.0" %}
{% set bliss_version = "0.73.2" %}

package:
  name: scipoptsuite
  version: {{ scip_version }}

source:
  - url: https://scip.zib.de/download/release/scipoptsuite-{{ scip_version }}.tgz
    sha256: f81b5a2c1c0eb949cf06bd50f42826e55284fa1269a6f28a92ac1a06d9c93a03
    folder: scipoptsuite
  - url: https://github.com/ds4dm/Bliss/archive/v{{ bliss_version }}.tar.gz
    sha256: 25278da769839a5feb88cbea4f36015b9092b2f111db9a2ea1c3080c8f6d109b
    folder: bliss

build:
  number: 5

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [unix]
  host:
    - boost-cpp
    - tbb-devel
    - libblas
    - zlib
    - gmp  # [unix]
    - ipopt
    - cppad
    - cliquer  # [unix]
    - bison  # [unix]
    - flex  # [unix]

outputs:

  - name: scip
    version: {{ scip_version }}
    build:
      run_exports:
        - {{ pin_subpackage('scip') }}
    requirements:
      build:
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - tbb-devel
        - libblas
        - zlib
        - gmp  # [unix]
        - ipopt
        - cppad
    files:
      - "lib/libscip*"
      - "lib/cmake/scip/"
      - "include/blockmemshell/"
      - "include/dijkstra/"
      - "include/lpi/"
      - "include/nlpi/"
      - "include/objscip/"
      - "include/scip/"
      - "include/symmetry/"
      - "include/tclique/"
      - "include/tinycthread/"
      - "include/tpi/"
      - "include/xml/"
      - "bin/scip"
    test:
      script: run_scip_test.sh  # [unix]
      script: run_scip_test.bat  # [win]
      source_files:
        - scipoptsuite/scip/examples/Queens
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - make  # [unix]

  - name: soplex
    version: {{ soplex_version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - zlib
        - gmp  # [unix]
        - boost-cpp
      run:
        # libboost_program_options.so needed by bin/soplex.
        # boost does not set run_exports so it is needed in run requirements.
        - boost-cpp
    files:
      - "lib/libsoplex*"
      - "lib/cmake/soplex/"
      - "include/soplex*"
      - "include/soplex/"
      - "bin/soplex"
    test:
      script: run_soplex_test.sh  # [unix]
      script: run_soplex_test.bat  # [win]
      source_files:
        - scipoptsuite/soplex/src/example.cpp
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - make  # [unix]

  - name: gcg
    version:  {{ gcg_version }}
    build:
      run_exports:
        - {{ pin_subpackage('gcg') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - gmp  # [unix]
        - cliquer  # [unix]
        - {{ pin_subpackage('scip', exact=True) }}
      run:
        - {{ pin_subpackage('scip') }}
        # run_exports not set for cliquer
        - cliquer  # [unix]
    files:
      - "lib/libgcg*"
      - "lib/cmake/gcg"
      - "include/gcg"
      - "bin/gcg"
    test:
      commands:
        - gcg --version
        - test -d "${PREFIX}/lib/cmake/gcg"  # [unix]
        - test -d "${PREFIX}/include/gcg"  # [unix]
        - if exist %LIBRARY_PREFIX%\lib\cmake\gcg (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\include\gcg (exit 0) else (exit 1)  # [win]

  - name: zimpl
    version: {{ zimpl_version }}
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - zlib
        - gmp  # [unix]
        - bison  # [unix]
        - flex  # [unix]
    files:
      - "lib/libzimpl*"
      - "lib/cmake/zimpl/"
      - "include/zimpl"
      - "bin/zimpl"
    test:
      commands:
        - zimpl -V
        - test -d "${PREFIX}/lib/cmake/zimpl"
        - test -d "${PREFIX}/include/zimpl"

about:
  home: https://scipopt.org/
  license: ZIB-Academic AND LGPL-3.0-or-later
  license_file:
    - scipoptsuite/COPYING
    - bliss/COPYING.LESSER
    - bliss/include/bliss/utils.hh
  summary: Mixed Integer Programming (MIP) solver and Branch-and-Cut-and-Price Framework

extra:
  recipe-maintainers:
    - AntoinePrv
    - pokutta
    - fschloesser
